version: '3.2'
services: 
       
     api-service:
        volumes:
            - ./api_rest/:/backend/
        build: ./api_rest
        working_dir: /backend/
        command: sh run_commands.sh
        ports:
            - "5000:5000"
        networks:
            - backend
       
networks:
  backend:
     driver: bridge