version: '3.2'
services: 
    api-service:
        build: ./api_rest/
        volumes: 
            - ./api_rest/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1