version: '3.2'
services: 
     postgres:
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            POSTGRES_HOST: localhost
        image: postgres:latest
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            
     api-service:
        volumes:
            - ./api_rest/:/backend/
        build: ./api_rest
        working_dir: /backend/
        command: sh run_commands.sh
        ports:
            - "5000:5000"
        networks:
            - backend
        depends_on:
            postgres:
                condition: service_healthy

networks:
  backend:
     driver: bridge