version: '3.2'
services: 
     postgres:
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            POSTGRES_HOST: localhost
        image: postgres:latest
        networks:
            - backend
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

     api-service:
        build: ./api_rest/
        volumes: 
            - ./api_rest/:/usr/src/app/
        networks:
            - backend
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
        depends_on:
            - postgres
volumes:
  postgres_data:

networks:
  backend:
     driver: bridge